import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/header/Navbar";
import Provider from "@/components/Provider";
import { ClerkProvider } from "@clerk/nextjs";
import "react-loading-skeleton/dist/skeleton.css";
import "simplebar-react/dist/simplebar.min.css";

import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SummaQ",
  description: "Generated by Jutech Dev",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Provider>
          <body
            className={cn(
              `min-h-screen font-sans antialiased grainy`,
              inter.className
            )}
          >
            <Toaster />
            <Navbar />
            {children}
          </body>
        </Provider>
      </html>
    </ClerkProvider>
  );
}
